[theme]
primaryColor = "#f59e0b"
backgroundColor = "#f4f6fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#1f2937"
font = "sans-serif"

[server]
headless = true
runOnSave = false

[browser]
gatherUsageStats = false
